version: '1.0.{build}'
image: Visual Studio 2017
environment:
  matrix:
  # node.js
    - nodejs_version: "6"
branches:
  only:
  - master
install:
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Install-Product node $env:nodejs_version
  - IF %nodejs_version% LSS 4 npm -g install npm@2
  - set PATH=%APPDATA%\npm;%PATH%
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: cd ./src
  # Install node packages
  - cmd: npm install
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish -c Release -o .\release\
  - cmd: dir
after_build:
  # For once the build has completed
artifacts:
 - path: '.\release\'
   name: WebSite
   type: WebDeployPackage
clone_depth: 1
deploy: off